// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    Button: typeof import('./components/Button.vue')['default']
    Counter: typeof import('./components/Counter.vue')['default']
    Footer: typeof import('./components/Footer.vue')['default']
    Icon: typeof import('./components/Icon.vue')['default']
    NavBar: typeof import('./components/NavBar.vue')['default']
    ProjectCard: typeof import('./components/ProjectCard.vue')['default']
    README: typeof import('./components/README.md')['default']
    TechStack: typeof import('./components/TechStack.vue')['default']
    TestComp: typeof import('./components/TestComp.vue')['default']
  }
}

export { }
